#!/bin/sh

set casa = `pwd`
echo $casa

nsls -padCASTOR- | grep -key- > files

for rootfile in `head -n -fin- files | tail -n -step-`
        do
        echo $rootfile
        rfcp -padCASTOR-/$rootfile .
        done

ls *.root > listoffilesLocal-ini---fin-.txt

cd -padtorun-
eval `scramv1 ru -sh`
cd -

hadd Local-ini---fin-.root -key-*

cp listoffilesLocal-ini---fin-.txt -currentpad-
rfcp Local-ini---fin-.root -padCASTOR-
exit 0

